In [36]:
import pickle

result_dict = pickle.load(open("./test.pkl", "rb"))   # 从输出pickle中读取数据

In [37]:
result_dict.keys()

dict_keys(['summary', 'stock_account', 'trades', 'stock_positions', 'benchmark_portfolio', 'portfolio'])

In [38]:
result_dict["portfolio"]

            avg_price  last_price  market_value order_book_id  quantity symbol
date
2018-02-02      14.05       14.05       99755.0   000001.XSHE      7100   平安银行
2018-02-05      36.99       36.99       99873.0   000002.XSHE      2700    万科A
2018-02-05      14.05       14.55           0.0   000001.XSHE         0   平安银行
2018-02-06      36.99       35.82           0.0   000002.XSHE         0    万科A
2018-02-06      14.00       14.00       99400.0   000001.XSHE      7100   平安银行
2018-02-07      32.98       32.98       89046.0   000002.XSHE      2700    万科A
2018-02-07      14.00       12.92           0.0   000001.XSHE         0   平安银行
2018-02-08      32.98       32.75           0.0   000002.XSHE         0    万科A
2018-02-08      12.54       12.54       90288.0   000001.XSHE      7200   平安银行
2018-02-09      31.27       31.27       84429.0   000002.XSHE      2700    万科A
2018-02-09      12.54       11.69           0.0   000001.XSHE         0   平安银行
2018-02-12      31.27       31.90           0.0   000002.XSHE         0    万科A
2018-02-12      11.72       11.72       85556.0   000001.XSHE      7300   平安银行
2018-02-13      32.73       32.73       85098.0   000002.XSHE      2600    万科A
2018-02-13      11.72       11.94           0.0   000001.XSHE         0   平安银行
2018-02-14      32.73       33.17           0.0   000002.XSHE         0    万科A
2018-02-14      12.00       12.00       87600.0   000001.XSHE      7300   平安银行
2018-02-22      33.70       33.70       90990.0   000002.XSHE      2700    万科A
2018-02-22      12.00       12.46           0.0   000001.XSHE         0   平安银行
2018-02-23      33.70       34.72           0.0   000002.XSHE         0    万科A
2018-02-23      12.61       12.61       93314.0   000001.XSHE      7400   平安银行
2018-02-26      34.18       34.18       92286.0   000002.XSHE      2700    万科A
2018-02-26      12.61       12.63           0.0   000001.XSHE         0   平安银行
2018-02-27      34.18       32.90           0.0   000002.XSHE         0    万科A
2018-02-27      12.28       12.28       89644.0   000001.XSHE      7300   平安银行
2018-02-28      32.70       32.70       88290.0   000002.XSHE      2700    万科A
2018-02-28      12.28       12.05           0.0   000001.XSHE         0   平安银行

In [35]:
result_dict["trades"]

,commission,exec_id,last_price,last_quantity,order_book_id,order_id,position_effect,side,symbol,tax,trading_datetime,transaction_cost
datetime,,,,,,,,,,,,
2018-02-02 09:30:00,79.0088,1523598566,13.91,7100,000001.XSHE,1523598566,None,BUY,平安银行,0.000,2018-02-02 15:30:00,79.0088
2018-02-05 09:30:00,78.3840,1523598567,13.80,7100,000001.XSHE,1523598567,None,SELL,平安银行,97.980,2018-02-05 15:30:00,176.3640
2018-02-05 09:30:00,76.5440,1523598568,36.80,2600,000002.XSHE,1523598568,None,BUY,万科A,0.000,2018-02-05 15:30:00,76.5440
2018-02-06 09:30:00,74.7344,1523598569,35.93,2600,000002.XSHE,1523598569,None,SELL,万科A,93.418,2018-02-06 15:30:00,168.1524
2018-02-06 09:30:00,76.2728,1523598570,14.23,6700,000001.XSHE,1523598570,None,BUY,平安银行,0.000,2018-02-06 15:30:00,76.2728
2018-02-07 09:30:00,76.2192,1523598571,14.22,6700,000001.XSHE,1523598571,None,SELL,平安银行,95.274,2018-02-07 15:30:00,171.4932
2018-02-07 09:30:00,75.7744,1523598572,36.43,2600,000002.XSHE,1523598572,None,BUY,万科A,0.000,2018-02-07 15:30:00,75.7744
2018-02-08 09:30:00,68.6400,1523598573,33.00,2600,000002.XSHE,1523598573,None,SELL,万科A,85.800,2018-02-08 15:30:00,154.4400
2018-02-08 09:30:00,68.7688,1523598574,12.83,6700,000001.XSHE,1523598574,None,BUY,平安银行,0.000,2018-02-08 15:30:00,68.7688
2018-02-09 09:30:00,64.7488,1523598575,12.08,6700,000001.XSHE,1523598575,None,SELL,平安银行,80.936,2018-02-09 15:30:00,145.6848
2018-02-09 09:30:00,63.0000,1523598576,31.50,2500,000002.XSHE,1523598576,None,BUY,万科A,0.000,2018-02-09 15:30:00,63.0000
2018-02-12 09:30:00,62.8600,1523598577,31.43,2500,000002.XSHE,1523598577,None,SELL,万科A,78.575,2018-02-12 15:30:00,141.4350
2018-02-12 09:30:00,65.0256,1523598578,11.78,6900,000001.XSHE,1523598578,None,BUY,平安银行,0.000,2018-02-12 15:30:00,65.0256
2018-02-13 09:30:00,65.5224,1523598579,11.87,6900,000001.XSHE,1523598579,None,SELL,平安银行,81.903,2018-02-13 15:30:00,147.4254
2018-02-13 09:30:00,64.5600,1523598580,32.28,2500,000002.XSHE,1523598580,None,BUY,万科A,0.000,2018-02-13 15:30:00,64.5600
2018-02-14 09:30:00,65.7400,1523598581,32.87,2500,000002.XSHE,1523598581,None,SELL,万科A,82.175,2018-02-14 15:30:00,147.9150
2018-02-14 09:30:00,66.0192,1523598582,11.96,6900,000001.XSHE,1523598582,None,BUY,平安银行,0.000,2018-02-14 15:30:00,66.0192
2018-02-22 09:30:00,67.6200,1523598583,12.25,6900,000001.XSHE,1523598583,None,SELL,平安银行,84.525,2018-02-22 15:30:00,152.1450
2018-02-22 09:30:00,65.2800,1523598584,34.00,2400,000002.XSHE,1523598584,None,BUY,万科A,0.000,2018-02-22 15:30:00,65.2800
2018-02-23 09:30:00,65.0880,1523598585,33.90,2400,000002.XSHE,1523598585,None,SELL,万科A,81.360,2018-02-23 15:30:00,146.4480
2018-02-23 09:30:00,67.4288,1523598586,12.58,6700,000001.XSHE,1523598586,None,BUY,平安银行,0.000,2018-02-23 15:30:00,67.4288
2018-02-26 09:30:00,68.4472,1523598587,12.77,6700,000001.XSHE,1523598587,None,SELL,平安银行,85.559,2018-02-26 15:30:00,154.0062
2018-02-26 09:30:00,67.3344,1523598588,35.07,2400,000002.XSHE,1523598588,None,BUY,万科A,0.000,2018-02-26 15:30:00,67.3344
2018-02-27 09:30:00,65.6640,1523598589,34.20,2400,000002.XSHE,1523598589,None,SELL,万科A,82.080,2018-02-27 15:30:00,147.7440
2018-02-27 09:30:00,65.7280,1523598590,12.64,6500,000001.XSHE,1523598590,None,BUY,平安银行,0.000,2018-02-27 15:30:00,65.7280
2018-02-28 09:30:00,62.9200,1523598591,12.10,6500,000001.XSHE,1523598591,None,SELL,平安银行,78.650,2018-02-28 15:30:00,141.5700
2018-02-28 09:30:00,62.4192,1523598592,32.51,2400,000002.XSHE,1523598592,None,BUY,万科A,0.000,2018-02-28 15:30:00,62.4192

In [13]:
"1" in ["3","2"]

False